enum BlendMode {
  PASS_THROUGH = "pass",
  NORMAL = "norm",
  DISSOLVE = "diss",
  DARKEN = "dark",
  MULTIPLY = "mul ",
  COLOR_BURN = "idiv",
  LINEAR_BURN = "lbrn",
  DARKER_COLOR = "dkCl",
  LIGHTEN = "lite",
  SCREEN = "scrn",
  COLOR_DODGE = "div ",
  LINEAR_DODGE = "lddg",
  LIGHTER_COLOR = "lgCl",
  OVERLAY = "over",
  SOFT_LIGHT = "sLit",
  HARD_LIGHT = "hLit",
  VIVID_LIGHT = "vLit",
  LINEAR_LIGHT = "lLit",
  PIN_LIGHT = "pLit",
  HARD_MIX = "hMix",
  DIFFERENCE = "diff",
  EXCLUSION = "smud",
  SUBTRACT = "fsub",
  DIVIDE = "fdiv",
  HUE = "hue ",
  SATURATION = "sat ",
  COLOR = "colr",
  LUMINOSITY = "lum ",
}

export default BlendMode;